# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BM' do
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'BMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
